# User Roles
ADMIN_ROLE = "ADMIN"
HOD_ROLE = "HOD"
GUARD_ROLE = "GUARD"
VISITOR_ROLE = "VISITOR"

# Visitor Application Status
APPLICATION_PENDING = "PENDING"
APPLICATION_APPROVED = "APPROVED"
APPLICATION_REJECTED = "REJECTED"

# Gate Pass Status
PASS_ACTIVE = "ACTIVE"
PASS_EXPIRED = "EXPIRED"
PASS_REVOKED = "REVOKED"